name: readme-topics
run-name: Update README.md with repos categorized by topic
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  generate-topics:
    runs-on: ubuntu-latest
    steps:
      - uses: metaory/github-readme-topics-action@v1
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        with:
          EMAIL: metaory@gmail.com
          TOPICS: |-
            api
            automation
            challenge
            cli
            github-actions
            npm-package
            theme
